service: temperatures

provider:
  name: aws
  runtime: python3.6
  timeout: 3
  memorySize: 128
  versionFunctions: false
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:Get*"
        - "cloudwatch:List*"
        - "cloudwatch:PutMetricData"
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"

custom:
  accountId: ${file(../awsAccountSettings.yml):accountId}

functions:
  handleTemperature:
    handler: handler.temperature
    events:
      - iot:
          sql: "SELECT * FROM 'temperatureMetric/#'"

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
